/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class khordr_KeyGrabber */

#ifndef _Included_khordr_KeyGrabber
#define _Included_khordr_KeyGrabber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     khordr_KeyGrabber
 * Method:    grab
 * Signature: (Lkhordr/KeyEventHandler;)V
 */
JNIEXPORT void JNICALL Java_khordr_KeyGrabber_grab
  (JNIEnv *, jclass, jobject);

/*
 * Class:     khordr_KeyGrabber
 * Method:    send
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_khordr_KeyGrabber_send
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
